apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: prometheus-kube-prometheus-alerts
  namespace: monitoring
  labels:
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/name: kube-prometheus
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 69.2.1
    prometheus: kube-prometheus
    role: alert-rules
    release: prometheus-kube-prometheus
spec:
  groups:
  - name: custom-node-alerts
    rules:
    - alert: customAlertNodeDown
      expr: up{job="node-exporter"} == 0
      for: 1m
      labels:
        severity: critical
        team: devops
      annotations:
        summary: "Node Down"
        description: "Node: {{ $labels.instance }}"
    
    - alert: customAlertNodeNotReady
      expr: kube_node_status_condition{condition="Ready",status="true"} == 0
      for: 1m
      labels:
        severity: warning
        team: devops
      annotations:
        summary: "Node Not Ready"
        description: "Node: {{ $labels.node }}"
    
    - alert: customAlertNodeCPU80
      expr: (1 - avg by (node) (rate(node_cpu_seconds_total{mode="idle"}[5m]))) * 100 > 80
      for: 5m
      labels:
        severity: warning
        team: devops
      annotations:
        summary: "Node CPU > 80%"
        description: "Node: {{ $labels.node }}"
    
    - alert: customAlertNodeCPU90
      expr: (1 - avg by (node) (rate(node_cpu_seconds_total{mode="idle"}[5m]))) * 100 > 90
      for: 5m
      labels:
        severity: critical
        team: devops
      annotations:
        summary: "Node CPU > 90%"
        description: "Node: {{ $labels.node }}"
    
    - alert: customAlertNodeMemory80
      expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 80
      for: 5m
      labels:
        severity: warning
        team: devops
      annotations:
        summary: "Node Memory > 80%"
        description: "Node: {{ $labels.node }}"
    
    - alert: customAlertNodeMemory90
      expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 90
      for: 5m
      labels:
        severity: critical
        team: devops
      annotations:
        summary: "Node Memory > 90%"
        description: "Node: {{ $labels.node }}"

  - name: custom-pod-alerts
    rules:
    - alert: customAlertPodCrashLooping
      expr: rate(kube_pod_container_status_restarts_total[15m]) * 60 * 15 > 0
      for: 1m
      labels:
        severity: warning
        team: devops
      annotations:
        summary: "Pod Crash Looping"
        description: "Namespace: {{ $labels.namespace }}\nPod: {{ $labels.pod }}"
    
    - alert: customAlertPodNotReady
      expr: kube_pod_status_ready{condition="true"} == 0
      for: 1m
      labels:
        severity: warning
        team: devops
      annotations:
        summary: "Pod Not Ready"
        description: "Namespace: {{ $labels.namespace }}\nPod: {{ $labels.pod }}"
    
    - alert: customAlertPodFailed
      expr: kube_pod_status_phase{phase="Failed"} == 1
      for: 1m
      labels:
        severity: critical
        team: devops
      annotations:
        summary: "Pod Failed"
        description: "Namespace: {{ $labels.namespace }}\nPod: {{ $labels.pod }}"

